services:
  ###########
  # Modules #
  ###########
  synthesis:
    image: ${IMAGE}
    container_name: synthesis
    ports:
      - 2000:2000
    command: 'python3 wei/tests/test_module/test_rest_node.py
      --port 2000
      --alias synthesis'
  transfer:
    image: ${IMAGE}
    container_name: transfer
    ports:
      - 2001:2001
    command: 'python3 wei/tests/test_module/test_rest_node.py
      --port 2001
      --alias transfer'
  measure:
    image: ${IMAGE}
    container_name: measure
    ports:
      - 2002:2002
    command: 'python3 wei/tests/test_module/test_rest_node.py
      --port 2002
      --alias measure'

  #####################
  # WEI Core Services #
  #####################
  wei_server:
    image: ${IMAGE}
    build:
      context: .
      dockerfile: ${DOCKERFILE}
      tags:
        - ${IMAGE}:latest
        - ${IMAGE}:dev
    container_name: wei_server
    ports:
      - 8000:8000
    volumes:
      - diaspora_config:/home/app/.diaspora
      - ./tests/workcells:/workcell_defs
      - ~/.wei:/home/app/.wei
      - ./:/home/app/wei # for development only
    environment:
      - PYTHONUNBUFFERED=1 # Fix weird bug with empty logging
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    command: python3 -m wei.server --workcell /workcell_defs/${WORKCELL_FILENAME}
    depends_on:
      - wei_redis
  wei_engine:
    image: ${IMAGE}
    container_name: wei_engine
    volumes_from:
      - wei_server
    environment:
      - PYTHONUNBUFFERED=1 # Fix weird bug with empty logging
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    command: python3 -m wei.engine --workcell /workcell_defs/${WORKCELL_FILENAME}
    depends_on:
      - wei_redis
      - wei_server
  wei_redis:
    image: redis
    container_name: wei_redis
    ports:
      - 6379:6379
    volumes:
      - ~/.wei/redis:/data
    command: 'redis-server
      --save 600 1
      --loglevel warning
      --appendonly yes'

################
# Data Storage #
################
volumes:
  diaspora_config:
    driver: local
