services:
  ###########
  # Dev App #
  ###########
  test_app:
    container_name: test_app
    image: ${IMAGE_TEST}
    build:
      context: tests/
      dockerfile: ${DOCKERFILE_TEST}
      tags:
        - ${IMAGE_TEST}:latest
        - ${IMAGE_TEST}:dev
    volumes:
      - ${WORKCELLS_DIR}:/workcell_defs
      - ${WEI_DATA_DIR}:/home/app/.wei
      - diaspora_config:/home/app/.diaspora
      - ${PROJECT_DIR}:/home/app/wei # for development only
    env_file:
      - .env
    profiles:
      - test
    command: pytest -p no:cacheprovider wei
    depends_on:
      - synthesis
      - transfer
      - measure
      - wei_server
      - wei_engine
      - wei_redis

  ###########
  # Modules #
  ###########
  synthesis:
    image: ${IMAGE_TEST}
    container_name: synthesis
    ports:
      - 2000:2000
    command: 'python3 wei/tests/test_module/test_rest_node.py
      --port 2000
      --alias synthesis'
  transfer:
    image: ${IMAGE_TEST}
    container_name: transfer
    ports:
      - 2001:2001
    command: 'python3 wei/tests/test_module/test_rest_node.py
      --port 2001
      --alias transfer'
  measure:
    image: ${IMAGE_TEST}
    container_name: measure
    ports:
      - 2002:2002
    command: 'python3 wei/tests/test_module/test_rest_node.py
      --port 2002
      --alias measure'

  #####################
  # WEI Core Services #
  #####################
  wei_server:
    image: ${IMAGE}
    build:
      context: .
      dockerfile: ${DOCKERFILE}
      tags:
        - ${IMAGE}:latest
        - ${IMAGE}:dev
    container_name: wei_server
    ports:
      - 8000:8000
    volumes:
      - ${WORKCELLS_DIR}:/workcell_defs
      - ${WEI_DATA_DIR}:/home/app/.wei
      - diaspora_config:/home/app/.diaspora
      - ${PROJECT_DIR}:/home/app/wei # for development only
    env_file:
      - .env
    command: python3 -m wei.server --workcell /workcell_defs/${WORKCELL_FILENAME} --use_diaspora ${USE_DIASPORA}
    depends_on:
      - wei_redis
  wei_engine:
    image: ${IMAGE}
    container_name: wei_engine
    volumes:
      - ${WORKCELLS_DIR}:/workcell_defs
      - ${WEI_DATA_DIR}:/home/app/.wei
      - ${PROJECT_DIR}:/home/app/wei # for development only
    environment:
     - PYTHONUNBUFFERED=1 # Fix weird bug with empty logging
    env_file:
      - .env
    command: python3 -m wei.engine --workcell /workcell_defs/${WORKCELL_FILENAME} --use_diaspora ${USE_DIASPORA}
    depends_on:
      - wei_redis
      - wei_server
  wei_redis:
    image: redis
    container_name: wei_redis
    ports:
      - 6379:6379
    volumes:
      - ${REDIS_DIR}:/data
    command: redis-server --save 60 1 --loglevel warning

################
# Data Storage #
################
volumes:
  diaspora_config:
    driver: local
