services:
  ###########
  # Modules #
  ###########
  synthesis:
    image: ${IMAGE}
    container_name: synthesis
    ports:
      - 2000:2000
    command: 'python3 wei/tests/test_module/test_rest_node.py
      --port 2000
      --alias synthesis'
  transfer:
    image: ${IMAGE}
    container_name: transfer
    ports:
      - 2001:2001
    command: 'python3 wei/tests/test_module/test_rest_node.py
      --port 2001
      --alias transfer'
  measure:
    image: ${IMAGE}
    container_name: measure
    ports:
      - 2002:2002
    command: 'python3 wei/tests/test_module/test_rest_node.py
      --port 2002
      --alias measure'

  #####################
  # WEI Core Services #
  #####################
  test_wei_server:
    image: ${IMAGE}
    build:
      context: .
      dockerfile: ${DOCKERFILE}
      tags:
        - ${IMAGE}:latest
        - ${IMAGE}:dev
    container_name: test_wei_server
    ports:
      - 8000:8000
    volumes:
      - diaspora_config:/home/app/.diaspora
      - ./tests/workcells:/workcell_defs
      - ~/.wei:/home/app/.wei
    environment:
      - PYTHONUNBUFFERED=1 # Fix weird bug with empty logging
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      - DATABASE_URL=postgresql://rpl:rpl@wei_postgres:5432/resources
    command: python3 -m wei.server --workcell /workcell_defs/${WORKCELL_FILENAME}
    depends_on:
      - test_wei_redis
      - wei_postgres

  test_wei_redis:
    image: redis
    container_name: test_wei_redis
    ports:
      - 6379:6379
    volumes:
      - ~/.wei/redis:/data
    command: 'redis-server
      --save 600 1
      --loglevel warning
      --appendonly yes'

####################
# PostgreSQL Setup #
####################
  wei_postgres:
    image: postgres:13
    container_name: wei_postgres
    environment:
      POSTGRES_USER: rpl
      POSTGRES_PASSWORD: rpl
      POSTGRES_DB: resources
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

################
# Data Storage #
################
volumes:
  diaspora_config:
    driver: local
  pgdata:
    driver: local
