version: "3.0"
services:
  ###########
  # Dev App #
  ###########
  test_app:
    container_name: ${APP_NAME}
    build:
      context: .
      dockerfile: ${DOCKERFILE_TEST}
      args:
          USER_ID: ${USER_ID}
          GROUP_ID: ${GROUP_ID}
    volumes:
      - ${WORKCELLS_DIR}:/workcell_defs
      - ${WEI_DATA_DIR}:/home/wei/.wei
      - diaspora_config:/home/wei/.diaspora
      - ${PROJECT_DIR}:/home/wei/wei # for development only
    depends_on:
      - wei_server
      - wei_engine
      - wei_redis
    tty: true
  #####################
  # WEI Core Services #
  #####################
  wei_server:
    image: ${IMAGE}
    container_name: wei_server
    ports:
      - 8000:8000
    volumes:
      - ${WORKCELLS_DIR}:/workcell_defs
      - ${WEI_DATA_DIR}:/home/wei/.wei
      - diaspora_config:/home/wei/.diaspora
      - ${PROJECT_DIR}:/home/wei/wei # for development only
    command: python3 -m wei.server --workcell /workcell_defs/${WORKCELL_FILENAME} --use_diaspora ${USE_DIASPORA}
    depends_on:
      - wei_redis
  wei_engine:
    image: ${IMAGE}
    container_name: wei_engine
    volumes:
      - ${WORKCELLS_DIR}:/workcell_defs
      - ${WEI_DATA_DIR}:/home/wei/.wei
      - ${PROJECT_DIR}:/home/wei/wei # for development only
    command: python3 -m wei.engine --workcell /workcell_defs/${WORKCELL_FILENAME} --use_diaspora ${USE_DIASPORA}
    depends_on:
      - wei_redis
      - wei_server
  wei_redis:
    image: redis
    container_name: wei_redis
    ports:
      - 6379:6379
    volumes:
      - ${REDIS_DIR}:/data
    command: redis-server --save 60 1 --loglevel warning

################
# Data Storage #
################
volumes:
  diaspora_config:
    driver: local
