version: "3.0"
services:
  wei_server:
    image: wei
    container_name: wei_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: python -m wei.server --workcell /app/tests/test_workcell.yaml
    depends_on:
      - wei_redis
  wei_scheduler:
    image: wei
    container_name: wei_scheduler
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m wei.scheduler --workcell /app/tests/test_workcell.yaml --redis_host wei_redis
    depends_on:
      - wei_redis
      - sleeper_node
      - webcam_node
  wei_redis:
    image: redis
    container_name: wei_redis
    ports:
      - 6379:6379
    volumes:
      - ~/.wei/redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
  sleeper_node:
    image: wei
    container_name: sleeper_node
    build:
      context: .
      dockerfile: Dockerfile
    command: python /app/examples/example_clients/sleep_rest_node.py
    ports:
      - 2000:2000
  webcam_node:
    image: wei
    container_name: webcam_node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2001:2001
    command: python /app/examples/example_clients/webcam_rest_node.py
