FROM ghcr.io/ad-sdl/wei

######################################
# App specific changes go here       #
######################################

RUN --mount=type=cache,target=/root/.cache \
    pip install -r /home/app/wei/requirements/dev.txt

######################################
