/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export { }

declare module 'vue' {
  export interface GlobalComponents {
    CancelButton: typeof import('./src/components/AdminButtons/CancelButton.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    Event: typeof import('./src/components/Event.vue')['default']
    Experiments: typeof import('./src/components/Experiments.vue')['default']
    LocationsPanel: typeof import('./src/components/LocationsPanel.vue')['default']
    LockUnlockButton: typeof import('./src/components/AdminButtons/LockUnlockButton.vue')['default']
    ModulesPanel: typeof import('./src/components/ModulesPanel.vue')['default']
    ModuleModal: typeof import('./src/components/ModuleModal.vue')['default']
    PauseResumeButton: typeof import('./src/components/AdminButtons/PauseResumeButton.vue')['default']
    ResetButton: typeof import('./src/components/AdminButtons/ResetButton.vue')['default']
    SafetyStopButton: typeof import('./src/components/AdminButtons/SafetyStopButton.vue')['default']
    ShutdownButton: typeof import('./src/components/AdminButtons/ShutdownButton.vue')['default']
    Workflow: typeof import('./src/components/Workflow.vue')['default']
    WorkflowModal: typeof import('./src/components/WorkflowModal.vue')['default']
    WorkflowsPanel: typeof import('./src/components/WorkflowsPanel.vue')['default']
    WorkflowTable: typeof import('./src/components/WorkflowTable.vue')['default']
  }
}
