FROM jupyter/minimal-notebook:python-3.11

ARG USER=joyvan
ARG USER_ID=1000
ARG GROUP_ID=1000
ARG WEI_PATH=/home/${USER}/wei
ARG WEI_DATA_PATH=/home/${USER}/.wei

USER root

RUN git clone https://github.com/AD-SDL/wei.git -b main ${WEI_PATH}
RUN mkdir -p ${WEI_DATA_PATH}/temp
RUN chown -R ${USER_ID}:${GROUP_ID} ${WEI_DATA_PATH}

# Install dependencies and wei
RUN pip install pdm

WORKDIR ${WEI_PATH}
RUN pdm install --prod
