FROM jupyter/minimal-notebook:python-3.11

ARG USER=joyvan
ARG USER_ID=1000
ARG GROUP_ID=1000
ARG WEI_PATH=/home/${USER}/wei
ARG WEI_DATA_PATH=/home/${USER}/.wei

USER root

RUN mkdir -p ${WEI_PATH}
RUN mkdir -p ${WEI_DATA_PATH}/temp
RUN chown -R ${USER_ID}:${GROUP_ID} ${WEI_DATA_PATH}

# Copy wei files
COPY wei ${WEI_PATH}/wei
COPY tests ${WEI_PATH}/tests
COPY examples ${WEI_PATH}/examples
COPY pyproject.toml ${WEI_PATH}/pyproject.toml
COPY README.md ${WEI_PATH}/README.md


# Install dependencies and wei
# RUN pip install pdm

WORKDIR ${WEI_PATH}
RUN pip install -e '.[examples]'
# RUN pdm install -G examples
