FROM python:3.11

RUN mkdir /wei

# Copy wei files
COPY requirements /wei/requirements
COPY wei /wei/wei
COPY tests /wei/tests
COPY setup.cfg /wei/setup.cfg
COPY setup.py /wei/setup.py
COPY examples /wei/examples


# Install dependencies
RUN python -m pip install --upgrade pip wheel setuptools && \
    pip install --no-cache-dir -r wei/requirements/requirements.txt && \
    pip install --no-cache-dir -r wei/requirements/dev.txt && \
    pip install --no-cache-dir -r wei/requirements/examples.txt

# Install wei
RUN pip install -e /wei
