name: Lint and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements/requirements.txt
          pip install -r requirements/dev.txt
          pip install .
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-complexity=14 --max-line-length=118 --statistics
      - name: Check code documentation
        run: |
          pydocstyle  --select=D100,D101,D102,D103,D104,D105,D106,D107 --match = ".*\.py"  .
      - name: Test with pytest
        run: |
          pytest -vs
