name: Pytest Unit Tests

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.12
      - name: Test with pytest
        run: make init build test
